### PR TITLE
Encoding and Help

### PR DESCRIPTION
**Pull request by schuellerf**
Hi!
I added support for input and output encoding as I needed this for my last name ;)

and in case of a wrong config all possible config parameters are printed to stderr.
I hope you like those changes
Regards

### CODE REVIEW

**Comment by schuellerf** [comment]
Sorry - this currently only works for python 2.
I'll fix this for python 3...

**Comment by vmiklos** [comment]
Thanks. The ged2dot header explicitly says python3, but I don't mind taking patches to work with python2 in case it does not break python3. :-)

**Comment by schuellerf** [comment]
With 4a41cdfa
Python3 should be ok

**Comment by vmiklos** [comment]
Hi,

Sorry for the extra slow feedback, I'll try to be quicker next time. :-)

So this still seems to break 'make check' for me with python 3.4; I can pastebin the exact output if you can't reproduce.

Regards,

Miklos

**Comment by schuellerf** [comment]
could have done this in advance :-|

please check bf01f04

**Comment by vmiklos** [comment]
@schuellerf do you have a test file with an encoding that is not UTF-8? The .ged file I get from ancestry.com has this:

```
1 CHAR UTF-8
```

I'm interested in adding a test file to the test suite that has e.g. latin1 encoding. I looked at the spec at https://www.familysearch.org/developers/docs/guides/gedcom it isn't really clear to me how to refer to latin1 there. Note that I'm primarily interested in automatic handling of the input encoding, so users don't have to specify it manually. Thanks.

I now regret I accepted this PR without a testcase. :-)

**Pull request merged**
